{
    "Service": "/Test/Services/RTOP.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/Test/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/Test/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}